### ISSUE TITLE
IndexError upon trying to run a test

### ISSUE THREAD

**Issue by AntonSax** [silverlight6/TFTMuZeroAgent#77]
I have a checkpoint from training and I want to test it out.
I used `python main.py --starting_episode 300 --test`

The program crashes with the following error message

> Traceback (most recent call last):
  File "C:\Users\Tony\Documents\Projects\TFTMuZeroAgent\TFTMuZeroAgent_source_code\main.py", line 49, in <module>
    main()
  File "C:\Users\Tony\Documents\Projects\TFTMuZeroAgent\TFTMuZeroAgent_source_code\main.py", line 26, in main
    test_interface.train_model(starting_train_step=args.starting_episode)
  File "C:\Users\Tony\Documents\Projects\TFTMuZeroAgent\TFTMuZeroAgent_source_code\TestInterface\test_ai_interface.py", line 38, in train_model
    data_workers.collect_gameplay_experience(env, buffers, weights)
  File "C:\Users\Tony\Documents\Projects\TFTMuZeroAgent\TFTMuZeroAgent_source_code\TestInterface\test_data_worker.py", line 57, in collect_gameplay_experience
    player_observation, info = env.reset(options={"default_agent": self.default_agent})
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tony\AppData\Local\Programs\Python\Python311\Lib\site-packages\pettingzoo\utils\conversions.py", line 181, in reset
    observations = {
                             ^
  File "C:\Users\Tony\AppData\Local\Programs\Python\Python311\Lib\site-packages\pettingzoo\utils\conversions.py", line 182, in <dictcomp>
    agent: self.aec_env.observe(agent)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tony\AppData\Local\Programs\Python\Python311\Lib\site-packages\pettingzoo\utils\wrappers\order_enforcing.py", line 101, in observe
    return super().observe(agent)
               ^^^^^^^^^^^^^^
  File "C:\Users\Tony\AppData\Local\Programs\Python\Python311\Lib\site-packages\pettingzoo\utils\wrappers\base.py", line 41, in observe
    return self.env.observe(agent)
              ^^^^^^^^^^^^^^^
  File "C:\Users\Tony\Documents\Projects\TFTMuZeroAgent\TFTMuZeroAgent_source_code\Simulator\tft_simulator.py", line 91, in observe
    "observations": self.player_manager.observation_states[agent].observation_to_input(initial_observation),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tony\Documents\Projects\TFTMuZeroAgent\TFTMuZeroAgent_source_code\Simulator\observation\vector\observation.py", line 512, in observation_to_input
    [
  File "C:\Users\Tony\Documents\Projects\TFTMuZeroAgent\TFTMuZeroAgent_source_code\Simulator\observation\vector\observation.py", line 515, in <listcomp>
    observation["opponents"][x]["board"],
    ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by silverlight6** [comment]
This is due to using the test interface. I have been making a lot of changes in the observation to turn it from vector to token based and also from using a separate opponent observation to having a combined one. These changes aren't updated in the test interface.
If you remove the --test, the rest should work as intended. 
I'll work on updating the test interface after I finish with my 2 experiments but that might be a little while.
